added sd card read. fix umtprd crash on large file by upgrade to 1.8.1.

diff --git a/board/rhodesisland/epass/rootfs/bin/umtpctl b/board/rhodesisland/epass/rootfs/bin/umtpctl
--- a/board/rhodesisland/epass/rootfs/bin/umtpctl
+++ b/board/rhodesisland/epass/rootfs/bin/umtpctl
@@ -24,6 +24,39 @@ start() {
     ln -s functions/ffs.mtp configs/c.1
     mkdir /dev/ffs-mtp
     mount -t functionfs mtp /dev/ffs-mtp
+
+    cp /etc/umtprd/umtprd_nosd.conf /etc/umtprd/umtprd.conf
+
+    start-stop-daemon -S -q -m -b -p /var/run/umtprd.pid -x /usr/sbin/umtprd
+    sleep 1
+    ls /sys/class/udc/ > /sys/kernel/config/usb_gadget/g1/UDC
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+
+auxstart() {
+    printf "Starting uMTPrd WITH SD CARD: "
+    mount none /sys/kernel/config -t configfs
+    mkdir /sys/kernel/config/usb_gadget/g1
+    cd /sys/kernel/config/usb_gadget/g1
+    mkdir configs/c.1
+    mkdir functions/ffs.mtp
+    mkdir strings/0x409
+    mkdir configs/c.1/strings/0x409
+
+    echo 0x0100 > idProduct
+    echo 0x1D6B > idVendor
+
+    echo "Rhodes Island" > strings/0x409/manufacturer
+    echo "Electric Pass" > strings/0x409/product
+
+    echo "Conf 1" > configs/c.1/strings/0x409/configuration
+    echo 120 > configs/c.1/MaxPower
+    ln -s functions/ffs.mtp configs/c.1
+    mkdir /dev/ffs-mtp
+    mount -t functionfs mtp /dev/ffs-mtp
+
+    cp /etc/umtprd/umtprd_sd.conf /etc/umtprd/umtprd.conf
+
     start-stop-daemon -S -q -m -b -p /var/run/umtprd.pid -x /usr/sbin/umtprd
     sleep 1
     ls /sys/class/udc/ > /sys/kernel/config/usb_gadget/g1/UDC
@@ -41,16 +74,14 @@ case "$1" in
     start)
     start
     ;;
+    auxstart)
+    auxstart
+    ;;
     stop)
     stop
     ;;
-    restart|reload)
-    stop
-    sleep 1
-    start
-    ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
+    echo "Usage: $0 {start|auxstart|stop}"
     exit 1
 esac
 
